### ISSUE TITLE
Add a datepicker on date inputs

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#116]
![capture d ecran 2015-03-02 a 18 01 29](https://cloud.githubusercontent.com/assets/1872808/6445712/2fee5d0e-c106-11e4-85f0-cd5148391502.png)

**Comment by ambroisemaupate** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker

**Comment by ambroisemaupate** [comment]
http://stackoverflow.com/a/15537698
