### ISSUE TITLE
Node type fields add form : autocomplete feature on "default values" when "children nodes" type is selected

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#119]
![capture d ecran 2015-03-09 a 16 44 52](https://cloud.githubusercontent.com/assets/1872808/6558337/f28afdf2-c67b-11e4-86d4-66787dad81b9.png)

**Comment by ambroisemaupate** [comment]
Implemented

WIP: We need to defined which fields to display according to node-type field type.
