### ISSUE TITLE
Install process documentation

### ISSUE THREAD

**Issue by Eternity-Yarr** [roadiz/roadiz#124]
You should mention explicitly requirements for folders ./cache and ./gen-src to be writable, as well as mod-rewrite module of webserver.

**Comment by Eternity-Yarr** [comment]
And many other write-permissions as well. E.g. if one cannot write conf/config.yml during database setup, there would be some cryptic error messages on the next step

**Comment by ambroisemaupate** [comment]
For the moment, this is mentioned in our read the docs: http://docs.roadiz.io/en/latest/intro/getting_started.html#requirements

We should add it in the requirements grid too. `mod-rewrite` should be a must-have module on Apache, especially for a CMS. I saw it was not default activated on WAMP/EasyPHP on Windows.

**Comment by Eternity-Yarr** [comment]
It isn't activated on debian either, one should manualy create symbolic link.

Good point about docs, I used "Installation" section of readme.md as on github, as guide. My bad.
