### ISSUE TITLE
Add image cropping feature in Document section.

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#13]
It will enable copying image links to be used directly in Markdown, even on other websites.

**Comment by Gouterman** [comment]
#251 Not relevant because not in Roadiz philosophy scope. We will add more display filters to process in front end templates instead.

**Comment by ambroisemaupate** [comment]
It could be relevant **only** if this tool is meant to crop images because the user does not have Photoshop to select an image part. This tool must not be used to prepare images *for the front-end*, this could be harmful for frontend development as this could prevent developer to choose the right image format for a given page.
