### ISSUE TITLE
Stack nodes list : add a select field to order on different criteria (position, date, etc.)

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#134]
![capture d ecran 2015-04-22 a 10 59 36](https://cloud.githubusercontent.com/assets/1872808/7270736/b1e46236-e8de-11e4-96b3-f72583987c3b.png)

**Comment by ambroisemaupate** [comment]
In a matter of fact, stack nodes lists are ordered with their container `children_ordering` fields in Node parameters.

![capture d ecran 2016-09-22 a 18 33 30](https://cloud.githubusercontent.com/assets/380026/18757201/2a39abb2-80f3-11e6-9273-f7f7e2de6465.png)
