### ISSUE TITLE
Installation theme is glitchy

### ISSUE THREAD

**Issue by Eternity-Yarr** [roadiz/roadiz#135]
One picture will be better than thousand words
![2015-04-22-220424_1147x768_scrot](https://cloud.githubusercontent.com/assets/3705333/7282873/73996712-e93b-11e4-9dfb-f72d083e4a52.png)

On the other hand theese strings are not the real translation, nevertheless, layout is broken.

**Comment by Eternity-Yarr** [comment]
with the real strings (which i submitting right now) its gonna be fine, though. So the issue is kinda minor.
![2015-04-22-221304_879x880_scrot](https://cloud.githubusercontent.com/assets/3705333/7283086/a033557a-e93c-11e4-9fe9-c229740291bf.png)

**Comment by ambroisemaupate** [comment]
Yes, I think someones didn’t understand how to translate Roadiz. They translate word by word keeping the periods. I will delete those string on crowndin. 

Thanks for your notice, we really appreciate.

**Comment by ambroisemaupate** [comment]
Will be fixed in 0.9.0
