### ISSUE TITLE
E-commerce

### ISSUE THREAD

**Issue by Olegatro** [roadiz/roadiz#142]
Hi, can I use cms for e-commerce?
How about tree ?

**Comment by ambroisemaupate** [comment]
Hi, 
Roadiz node system can handle any content type. You can create a `Product` node-type with a `price` and `stock` fields. But we didn’t code any shop cart or payment system.

What do you mean by *How about tree ?*

**Comment by Olegatro** [comment]
Hi, I mean tree architecture in traditional concept. Catalog -> subcatalog. 
I don't looked on of using node system. So, my question, maybe, is not correct.
I will install cms on holidays, and look more closely. Thanks for answer.

**Comment by ambroisemaupate** [comment]
Roadiz is not a specialized CMS. It’s a great advantage but it needs to well understand its polymorphic behaviour. You can shape your own tree structure with *categories*, *products* and *tags* but you have to think about your own architecture. Then we didn’t had time to build a starter e-commerce theme. Maybe it will come… someday :-)
