### ISSUE TITLE
Duplicate custom forms

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#166]
Duplicate a custom-form and all its custom-form fields. But without its answers of-course. :-)

**Comment by azokal** [comment]
I finished to implement it in the commit ef6ab84bad74ea2892b2a4f0200dbd410bef9e89.

**Comment by ambroisemaupate** [comment]
- [ ] Use $this->publishErrorMessage($request, $msg); because we don’t log errors
- [ ] We still have a persist cascade error 
![capture d ecran 2015-09-30 a 16 34 28](https://cloud.githubusercontent.com/assets/380026/10196071/3e753794-6791-11e5-8689-7dcbad450dee.png)
