### ISSUE TITLE
Create a cli jobs system

### ISSUE THREAD

**Issue by azokal** [roadiz/roadiz#167]
to be able to send newsletter in background task: #41.

**Comment by ambroisemaupate** [comment]
http://www.rabbitmq.com/tutorials/tutorial-one-php.html

Sending messages using crontab is bad. We need to use AMQP messaging protocol which is standard.  Then we can run a Roadiz *consumer* in background and use Rabbit MQ to receive and dispatch messages from Roadiz website.

**Comment by ambroisemaupate** [comment]
Closing. No need for this for the moment.

Symfony Messenger component is the best choice to implement such a feature, but on theme side. This is too specific to be included in Roadiz CMS.

https://symfony.com/doc/current/components/messenger.html
