### ISSUE TITLE
Problem during installing Roadiz

### ISSUE THREAD

**Issue by Tthaddee** [roadiz/roadiz#168]
Hello, 

I'm trying to install Roadiz on my own server. I've uploaded all the files at the root folder. But when i want to open it, it asking me to choose the language (french for me (sorry for my bad english :/ ) ) but since, everything i get is : 

Roadiz has lost its musicians
The Symfony\Component\Intl\Locale\Locale::setDefault() is not implemented. Please install the "intl" extension for full localization capabilities.
Please contact your site administrator, or post an issue on Github with following informations:

#0 /mnt/HD/HD_a2/Nas_Prog/WordPress/WordPress/themes/Install/InstallApp.php(71): Symfony\Component\Intl\Locale\Locale::setDefault('fr')
#1 /mnt/HD/HD_a2/Nas_Prog/WordPress/WordPress/src/Roadiz/Core/Services/RoutingServiceProvider.php(132): Themes\Install\InstallApp::setupDependencyInjection(Object(Pimple\Container))
#2 /mnt/HD/HD_a2/Nas_Prog/WordPress/WordPress/vendor/pimple/pimple/src/Pimple/Container.php(112): RZ\Roadiz\Core\Services\RoutingServiceProvider->RZ\Roadiz\Core\Services\{closure}(Object(Pimple\Container))
#3 /mnt/HD/HD_a2/Nas_Prog/WordPress/WordPress/src/Roadiz/Core/Kernel.php(341): Pimple\Container->offsetGet('routeCollection')
#4 /mnt/HD/HD_a2/Nas_Prog/WordPress/WordPress/index.php(64): RZ\Roadiz\Core\Kernel->initEvents()
#5 {main}

Someone can help me please ?

Thanks ;)
T

**Comment by Tthaddee** [comment]
Precision : Yes, i've willingly installed in a folder called "Wordpress". It's not a mistake.

**Comment by azokal** [comment]
On which OS are you ?
If it's Ubuntu or Debian. Do a sudo apt-get install php5-intl.
Normally, it will fix this error.

**Comment by Tthaddee** [comment]
I don't know wich OS it is exactly. I want to run it on a Western Digital MyCloud 2Ex nas. Thanks for the idea, i'll try something

**Comment by azokal** [comment]
" Please install the "intl" extension for full localization capabilities." This error means you need to enable/install the php extension "intl". I don't know you system so I can't help you more.

**Comment by Tthaddee** [comment]
Ok, I've done another installation on a local server under Ubuntu 14.04 (ElementaryOS, but it's the same). I can access the first page properly, but when I begin the installation, I have a 404 : 

"The requested URL /www/install/check-requirements was not found on this server."

**Comment by Tthaddee** [comment]
After some verifications, I don't have a "/install/check-requirements"... oO"

**Comment by ambroisemaupate** [comment]
Hi @Tthaddee, did you install using Git or the bundled ZIP archive ? It seems that your URL rewriting is not enabled. Do you have `mod_rewrite` enabled on your Apache ?

**Comment by Tthaddee** [comment]
I'm using the bundled zip. Yes, the mod_rewrite.so is enabled :/

**Comment by ambroisemaupate** [comment]
Does your Apache configuration allow .htaccess override ? Or did you use Roadiz samples to create your Apache virtual host ?

**Comment by Tthaddee** [comment]
I've this line in my "./opt/lampp/apache2/conf/httpd.conf" file : 

AccessFileName .htaccess

**Comment by C4Grey** [comment]
Same issue, Apache 2.4 on Windows 8.1.

**Comment by azokal** [comment]
Hi @C4Grey,
For your problem, I was able to reproduce the bug with wamp.

This problem is caused by not found php DLL by apache.

To solve it:
- check is the VC redist 2012 is correctly install (if you use 5.5 php).
- check if the PHP extension is activated (php-intl).
- Add the PHP path (C:\wamp\bin\php\php5.5.12 for me) to your system path. Or just copy all DLL which start by "icu" that you can find in the PHP folder in your apache folder (C:\wamp\bin\apache\apache2.4.9 for me).

**Comment by azokal** [comment]
By the way, @C4Grey your issue is not related to @Tthaddee issue.
