### ISSUE TITLE
[BUG] Can't access backoffice on a Wamp install with postgreSQL

### ISSUE THREAD

**Issue by itanea** [roadiz/roadiz#169]
Hello RoadizTeam, 

After a fresh local installation (download archive from official website - version 0.10 alpha) to test Roadiz that works prefectly.
Frontend part works well ;-).

**Config environment :**
* Wamp
  * PHP 5.4.13
  * php_pdo_pgsql extension activated
*  postgresql 9.4

Backoffice connextion via /rz-admin give me the following error message :

**Error message :**

Roadiz has lost its musicians
An exception occurred while executing 'SELECT n0_.id AS id_0, n0_.title AS title_1, n0_.meta_title AS meta_title_2, n0_.meta_keywords AS meta_keywords_3, n0_.meta_description AS meta_description_4, n1_.content AS content_5, n3_.content AS content_6, max(l4_.datetime) AS sclr_7, n0_.discr AS discr_8, n0_.node_id AS node_id_9, n0_.translation_id AS translation_id_10 FROM nodes_sources n0_ LEFT JOIN ns_basicblock n1_ ON n0_.id = n1_.id LEFT JOIN ns_neutral n2_ ON n0_.id = n2_.id LEFT JOIN ns_page n3_ ON n0_.id = n3_.id INNER JOIN log l4_ ON n0_.id = l4_.node_source_id GROUP BY n0_.id ORDER BY sclr_7 DESC LIMIT 4': SQLSTATE[42803]: Grouping error: 7 ERREUR: la colonne « n1_.content » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat LINE 1: ...ds_3, n0_.meta_description AS meta_description_4, n1_.conten... ^

Please contact your site administrator, or post an issue on Github with following informations:

#0 C:\wamp\www\roadiz-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php(116): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))

#1 C:\wamp\www\roadiz-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT n0_.id A...', Array)

#2 C:\wamp\www\roadiz-master\vendor\doctrine\orm\lib\Doctrine\ORM\Query\Exec\SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT n0_.id A...', Array, Array, NULL)

#3 C:\wamp\www\roadiz-master\vendor\doctrine\orm\lib\Doctrine\ORM\Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)

#4 C:\wamp\www\roadiz-master\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()

#5 C:\wamp\www\roadiz-master\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)

#6 C:\wamp\www\roadiz-master\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)

#7 C:\wamp\www\roadiz-master\src\Roadiz\Core\Repositories\NodesSourcesRepository.php(639): Doctrine\ORM\AbstractQuery->getResult()

#8 C:\wamp\www\roadiz-master\themes\Rozier\Controllers\DashboardController.php(52): RZ\Roadiz\Core\Repositories\NodesSourcesRepository->findByLatestUpdated(4)

#9 [internal function]: Themes\Rozier\Controllers\DashboardController->indexAction(Object(RZ\Roadiz\Core\HttpFoundation\Request))

#10 C:\wamp\www\roadiz-master\vendor\symfony\http-kernel\HttpKernel.php(147): call_user_func_array(Array, Array)

#11 C:\wamp\www\roadiz-master\vendor\symfony\http-kernel\HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(RZ\Roadiz\Core\HttpFoundation\Request), 1)

#12 C:\wamp\www\roadiz-master\src\Roadiz\Core\Kernel.php(222): Symfony\Component\HttpKernel\HttpKernel->handle(Object(RZ\Roadiz\Core\HttpFoundation\Request))

#13 C:\wamp\www\roadiz-master\index.php(65): RZ\Roadiz\Core\Kernel->runApp()

#14 {main}

Do not hesitate to contact me if need clarification !

**Comment by ambroisemaupate** [comment]
Hi @itanea, we managed to reproduce your issue. We are looking for a fix. For the moment, you can test it using MySQL or SQLite.

**Comment by ambroisemaupate** [comment]
It seems to be related to a bug in Doctrine: http://www.doctrine-project.org/jira/browse/DDC-2917

**Comment by ambroisemaupate** [comment]
@itanea issue was fixed, please upgrade to v0.10.1. Thank you for your feedback! Cheers
