### ISSUE TITLE
Rebuild default theme with BaseTheme

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#170]

**Comment by ambroisemaupate** [comment]
- Use Bootstrap instead of UIKit
- Add a BasicBlock node-type with node examples inside pages.

**Comment by AdsonCicilioti** [comment]
Why switch to Bootstrap?

**Comment by ambroisemaupate** [comment]
This issue has been closed almost a year ago. 

Bootstrap has been choosed to get better cohesion with BaseTheme which is our starter kit for all projects.
