### ISSUE TITLE
Enhance adding tag feature on nodes

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#179]
When we want to add a tag, we have no idea about the existing tags. We could open a panel (like node & documents) or something like that.

![capture d ecran 2015-10-15 a 10 00 36](https://cloud.githubusercontent.com/assets/1872808/10507885/0e25f8dc-7324-11e5-8add-e5be2ea7edb9.png)

**Comment by ambroisemaupate** [comment]
![capture d ecran 2016-01-19 a 18 35 40](https://cloud.githubusercontent.com/assets/380026/12426732/75eeb730-bedb-11e5-9ffd-04b8ab71e3e9.png)

For the moment tags stay in the edition field and act like real tags.

We need now to build a Tag explorer.

**Comment by ambroisemaupate** [comment]
Use a combobox with all tags, not only the one you are searching.

**Comment by ambroisemaupate** [comment]
Implemented with style by @Gouterman
