### ISSUE TITLE
Enhance translate nodes actions

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#180]
- [x] We need to move the *Translate* action to a better location to prevent user to go into *Parameters* section. Maybe adding a button aside with translation menu.
- [x] We need to be able to translate every node’ children (for page blocks). Translating them one by one is a pain.

**Comment by maximeberard** [comment]
![capture d ecran 2015-10-22 a 11 56 20](https://cloud.githubusercontent.com/assets/1872808/10934827/78a0ae8c-82e2-11e5-843a-bc7e62d7c8b5.png)

**Comment by ambroisemaupate** [comment]
This will be available in next release.
