### ISSUE TITLE
Add a "small" option on markdown fields to reduce textarea height

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#184]
![small-markdown](https://cloud.githubusercontent.com/assets/1872808/10934738/e5da9b44-82e1-11e5-97b9-ef9ad5fa8311.png)

**Comment by ambroisemaupate** [comment]
Anyway, I planned to rewrite the markdown editor directly on top of *CodeMirror* in order to get rid of *UIKit Html Editor*. We have performance issues on *Firefox* where the markdown editor takes 100% of CPU.

**Comment by ambroisemaupate** [comment]
See */feature/custom_markdown_editor* branch.

**Comment by ambroisemaupate** [comment]
![capture d ecran 2015-11-15 a 22 59 47](https://cloud.githubusercontent.com/assets/380026/11171279/964aed86-8bec-11e5-8e4e-67bd03a8f47f.png)
