### ISSUE TITLE
Problem installing from zip package

### ISSUE THREAD

**Issue by rafamds** [roadiz/roadiz#191]
Hi :)
I get this error when going to the url:

![screen shot 2016-01-11 at 13 50 53](https://cloud.githubusercontent.com/assets/924985/12235247/6f7e5404-b86a-11e5-8c9c-fc07e7c327f8.jpg)

Any idea of what is happening? Maybe I missed a step
thanks

**Comment by ambroisemaupate** [comment]
Hello @rafamds, did you run `yourdomain.ltd/install.php` in your browser before using Roadiz.

**Comment by ambroisemaupate** [comment]
If you are not running from localhost you will have to add your WAN IP address to the `install.php` file to access it from your browser.

**Comment by rafamds** [comment]
Oh so silly of me... I tried `/install` instead of `/install.php`. That solved it. Thanks @ambroisemaupate 
Another question, on my windows machine. I always get problem with the intl extension, what do you use this extension for in Roadiz.

Thanks for your help :+1:

**Comment by ambroisemaupate** [comment]
> Another question, on my windows machine. I always get problem with the intl extension, what do you use this extension for in Roadiz.

It’s used for formatting dates and currencies according to Locale: http://twig.sensiolabs.org/doc/extensions/intl.html

**Comment by azokal** [comment]
Hello,
If you are using wamp on windows, take care that you have this "C:\wamp\bin\php\php5.5.12" on your system Path.

**Comment by rafamds** [comment]
Thanks @ambroisemaupate and @azokal. 
You may close the issue as you wish :smile: 

Have a nice day
