### ISSUE TITLE
Problem when i logged in the admin interface

### ISSUE THREAD

**Issue by Weysan** [roadiz/roadiz#192]
I successfully installed roadiz, but an error occured when I tried to logged in the admin interface 

> An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT n0_.id AS id_0, n0_.created_at AS created_at_1, n0_.updated_at AS updated_at_2, n0_.position AS position_3, n0_.node_name AS node_name_4, n0_.dynamic_node_name AS dynamic_node_name_5, n0_.home AS home_6, n0_.visible AS visible_7, n0_.status AS status_8, n0_.locked AS locked_9, n0_.priority AS priority_10, n0_.hide_children AS hide_children_11, n0_.sterile AS sterile_12, n0_.children_order AS children_order_13, n0_.children_order_direction AS children_order_direction_14, n1_.id AS id_15, n1_.title AS title_16, n1_.meta_title AS meta_title_17, n1_.meta_keywords AS meta_keywords_18, n1_.meta_description AS meta_description_19, n1_.discr AS discr_20 FROM nodes n0_ INNER JOIN nodes_sources n1_ ON n0_.id = n1_.node_id INNER JOIN translations t2_ ON n1_.translation_id = t2_.id WHERE n0_.parent_node_id IS NULL AND n1_.translation_id = ? AND n0_.status <= ?) dctrn_result ORDER BY position_3 ASC LIMIT 100 OFFSET 0' with params [1, 30]: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.position_3' which is not in SELECT list; this is incompatible with DISTINCT") in "@Rozier/widgets/nodeTree/nodeTree.html.twig" at line 49.

Any idea?

**Comment by ambroisemaupate** [comment]
Hello, it seems that you installed *Roadiz* on a database that already contains other data. What is `dctrn_result.position_3` column ? It’s not a *Roadiz* one for sure.

You should always create a blank database for each application.

**Comment by Weysan** [comment]
It was blank! position_3 is created by Doctrine : 

> n0_.position AS position_3

here =>

> SELECT DISTINCT id_0 FROM (SELECT n0_.id AS id_0, n0_.created_at AS created_at_1, n0_.updated_at AS updated_at_2, n0_.position AS position_3,

**Comment by ambroisemaupate** [comment]
What is your DB Driver? Mysql? MariaDB? PostgreSQL? SQLite?

**Comment by Weysan** [comment]
MySQL

**Comment by ambroisemaupate** [comment]
I don’t get your error after installing a fresh 0.13 Roadiz. Could you list precisely your environment and what Roadiz version do you use?

Did you setup the DefaultTheme during te install process?

**Comment by Weysan** [comment]
Okay, I tried in a WAMP environment (PHP 5.4), it works well.

I tried with a docker machine (PHP7), it didn't work, same error after installing successfully the CMS (for your information, the docker config : https://github.com/CouleurCitron/docker-php7 )

**Comment by ambroisemaupate** [comment]
Maybe it’s due to your *opcache* config. Could you try after disabling it ?

You can use our Vagrant built-in this repository. It’s working with PHP7 too and I don’t have any issue. I’ll try to mimic your *docker-php7* environment in Vagrant.

**Comment by Weysan** [comment]
Ok, you're right, seems to be an PHP7's opcache issue with doctrine : 
http://stackoverflow.com/questions/34958319/phpdocumentor-2-and-php-7-with-opcache-issues-in-doctrine

**Comment by ambroisemaupate** [comment]
Thanks for your investigation ! Is it just a PHP 7.0.2 issue? Because we are using 7.0.3 version on our Vagrant and our [docker](https://hub.docker.com/r/ambroisemaupate/roadiz/).
