### ISSUE TITLE
500 Error With Docker Install

### ISSUE THREAD

**Issue by tylerwalters** [roadiz/roadiz#200]
I was trying to Roadiz set up to give a test run using following the instructions [here](https://github.com/roadiz/docker-image). Everything seemed to go smoothly during while running the docker commands, but I get a non-specific 500 error page when I try to load it.

The last things in the docker logs are:

```
2016-03-17 05:07:45,199 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-17 05:07:45,200 INFO success: nginx-config entered RUNNING state, process has stayed up  for > than 1 seconds (startsecs)
2016-03-17 05:07:45,200 INFO success: php5-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-17 05:07:45,200 INFO success: php5-fpm-config entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by ambroisemaupate** [comment]
Did you install Roadiz using install.php entry point ?

**Comment by tylerwalters** [comment]
I get the 500 error at the root url, and trying to access index.php. You can actually view it at [https://roadiz.tylerwalters.com/index.php](https://roadiz.tylerwalters.com/index.php) if that is helpful.

**Comment by tylerwalters** [comment]
I could have sworn I tried reaching install.php and got the 500 error, but I just tried again and install.php actually leads to a 404 error. Any idea why that would be omitted? 

You can see the errors here: 
[https://roadiz.tylerwalters.com/](https://roadiz.tylerwalters.com/)
[https://roadiz.tylerwalters.com/install.php](https://roadiz.tylerwalters.com/install.php)

**Comment by ambroisemaupate** [comment]
It seems that install.php file does not exists on your docker container. Could you check ? If it does not, try to install/update *composer* for Roadiz.

**Comment by tylerwalters** [comment]
The install.php did not appear to be present in the docker container. I ran ```composer update``` and ```composer install```. That did create an install.php file, but when accessing it I get a permissions error when accessing it in the browser: 'You are not allowed to access this file. Check install.php for more information.'

**Comment by ambroisemaupate** [comment]
Yes, that’s the normal behaviour. Like any symfony apps, Roadiz restrict access by IP for `install.php` and `dev.php` entry points. You should edit `install.php` to add your own IP address.

**Comment by tylerwalters** [comment]
I don't have any experience with symfony apps, so I was unaware of that. I was able to edit install.php to get access. Everything seems to be working correctly after that. Thanks for the help!
