### ISSUE TITLE
 Maximum execution time of 30 seconds exceeded when installing

### ISSUE THREAD

**Issue by ptraceur** [roadiz/roadiz#203]
This happens to me when installing database on XAMPP windows 10
```
Fatal error: Maximum execution time of 30 seconds exceeded in C:\root\playground\roadiz-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 57
```

Any idea what could this be?

**Comment by rooftoprafa** [comment]
I've extended it to 300 in my php.ini file and it all worked well

**Comment by ambroisemaupate** [comment]
Great, but it’s still weird that you hit the time limit on PDO stuff. Check if your database is well configured.
