### ISSUE TITLE
Export node with node references ?

### ISSUE THREAD

**Issue by mmind-hub** [roadiz/roadiz#206]
Hi,
When i use the export function on a node i have the good output of my data,
expect the linked documents and node references. 

Can you give me a tip to join this data in the export function ?
I get that this is in the exportAction in the NodesUtilsController

Thank you ! 
I love this cms this is my only downside :)

**Comment by ambroisemaupate** [comment]
Hi @mmind-hub 

Thanks for your feedback.
You’re totally right about the node export which is missing linked documents and nodes. 

We did not implemented yet as it means that we should import these linked documents and nodes before. OR we can ignore these links if the destination entity does not exist.

**Comment by mmind-hub** [comment]
Thank you,
i tried to understand how to get those linked documents, exploring the theme and the database structure but it looks quite complex :)
Is there an already-made request that can i could dupplicate from this export function to get this data ?

**Comment by ambroisemaupate** [comment]
I’m closing suggestion and abandoned issues. Feel free to reopen it on https://ask.roadiz.io/
