### ISSUE TITLE
Responsive Rozier theme

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#21]
- [ ] Add an alert when turn to landscape mode
- [ ] Enable again condition on `isMobile.any()` to init *RozierMobile`JS class in`main.js`

**Comment by ambroisemaupate** [comment]
Login page is not responsive

**Comment by maximeberard** [comment]
Be careful with header with long breadcrumb & title

![screenshot jun 9 2015 10 14 48 am](https://cloud.githubusercontent.com/assets/1872808/8797747/c89e46da-2f9d-11e5-91d2-1e0be7b1fc57.png)
