### ISSUE TITLE
Go back to node edit page after updating a document informations.

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#211]
[FR]

Pour légender des images à la chaîne, pas possible de revenir vers une sélection donnée, cela renvoie vers l'intégralité des documents.

Button _Go back to documents_.

**Comment by ambroisemaupate** [comment]
Add a referer information when clicking on Document thumbnail to go back to nodeSource editing after form submit.

**Comment by ambroisemaupate** [comment]
We have a regression with VueJS implementation @Gouterman

**Comment by azokal** [comment]
:scream:
