### ISSUE TITLE
[Users page] Enhance styles for small screens, all content is not visible or streched

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#214]
![capture d ecran 2016-07-27 a 15 12 25](https://cloud.githubusercontent.com/assets/1872808/18544480/0b7c3de8-7b35-11e6-8fe5-5a11b9caa036.png)

**Comment by ambroisemaupate** [comment]
Fixed in d98e83c904de19a8e94682a8b0f797b1233fd5ff
