### ISSUE TITLE
[Node type] Add a parameter to define if a node type is accessible via an URL

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#216]
Useful for sitemap generation and for disable "preview page" link for non-accessible node-types

![capture d ecran 2016-09-28 a 15 37 19](https://cloud.githubusercontent.com/assets/1872808/18915572/c469092e-8591-11e6-8eb8-f01f59971ae6.png)

**Comment by ambroisemaupate** [comment]
I’m working on it. It will be called `reachable` and will be defined on each node-type.
