### ISSUE TITLE
Media uploader won't open ( Dropzone issue )

### ISSUE THREAD

**Issue by martial** [roadiz/roadiz#219]
Multiple dropzone instances ( media uploader for document node field type )  for a node is causing issues

1 : open one media uploader 
2 : upload one file
3 : open another media uploader 

`Uncaught Error: Dropzone already attached`

This issue happens also randomly when trying to open multiple dropzone boxes

**Comment by ambroisemaupate** [comment]
If you close the first `dropzone` before opening the second one. The error does not occur.

So we have to close every existing instance before.
