### ISSUE TITLE
Add node status in node reference widget (with icon?)

### ISSUE THREAD

**Issue by maximeberard** [roadiz/roadiz#221]
![capture d ecran 2016-10-25 a 10 05 06](https://cloud.githubusercontent.com/assets/1872808/19677724/e8391a1a-9a9a-11e6-8476-986e1d4c9ac0.png)

**Comment by ambroisemaupate** [comment]
![capture d ecran 2016-11-09 a 10 49 30](https://cloud.githubusercontent.com/assets/380026/20134053/379b909e-a66a-11e6-9bc1-591b72ba19cc.png)
