### ISSUE TITLE
Is there a guide create a new translation for the cms itself?

### ISSUE THREAD

**Issue by ptraceur** [roadiz/roadiz#222]
Hi,
nice work with Roadiz.

Is there a guide create a new translation for the cms itself?

Thanks

**Comment by ambroisemaupate** [comment]
Hi,

Thanks for your interest in Roadiz. 
Every static translations for default theme and back office are available on our Crowdin account. You'll be able to translate strings in the language you want. 

https://crowdin.com/project/roadiz-cms
