### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#231]
I wanted to install roadiz on my server (local and production using composer. I did it, but when I go on the url localhost/install.php and I get an error 500 or this message : "You are not allowed to access this file. Check install.php for more information.". When I go on the url localhost/ I have the same error code. Can you help me please ? 

PS: if I install it with success, I will package your application to integrate it in Yunohost.
frju365

**Comment by ambroisemaupate** [comment]
Hi @frju365. Install, dev and clear_caches entry points are restricted by IP. Same as Symfony. 

To access them just add your local or global IP address to each file.

**Comment by frju365** [comment]
ok. thanks. it works now. But when I click to change the language(I'm french) or to continue the installation, I have a 404 error. Perhaps I have a problem in my nginx conf. An idea ?

**Comment by ambroisemaupate** [comment]
Thanks @frju365 for your contribution. Translations are managed on Crowdin http://translate.roadiz.io. 

German translation is already started but not finished, your help will be awesome !
