### ISSUE TITLE
Problème avec la création de l'utilisateur/ Problem with user creation.

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#241]
Bonjour,
J'ai un problème avec la création de l'utilisateur. J'ai tout installé en CLI et je rentre la commande dans mon terminal :  `cd /var/www/roadiz`(webroot) then I do a `sudo ./bin/roadiz user:create abld`.
Ensuite je rentre mon adresse mail : `win10@tutanota.com`. J'appuie ensuite 2 fois sur y pour `Backend User` et `Superuser`, et là j'obtiens une erreur : 
`
pi@yunohost:/var/www/roadiz $ sudo php bin/roadiz users:create abld
Email : win10@tutanota.com
Is user a backend user? [y/N]: y
Is user a super-admin user? [y/N]: y
`
 `                                                                    
  [Swift_RfcComplianceException]                                     
  Address in mailbox given [] does not comply with RFC 2822, 3.6.2.  
`                                                                     
`
users:create <username>
`
`
pi@yunohost:/var/www/roadiz $ 
`
____
Ensuite, et c'est seulement une deuxième idée, ce serait de créer un seul fichier pour que l'utilisateur ait juste à taper une commande avec une suite d'argument afin que tout s'installe "d'un seul coup". Je pensais ici à abantecart, un site ecommerce écrit en php : 
je ai déjà packagé abantecart pour yunohost :
https://github.com/YunoHost-Apps/abantecart_ynh/blob/master/scripts/install#L101 ( une seule commande)
qui utilise le fichier en php de abantecart : 
https://github.com/abantecart/abantecart-src/blob/master/public_html/install/cli_install.php

En fait, mon objectif est de packager roadiz pour Yunohost, logiciel opensource pour l'auto-hébergement (structure + sécurité + automatisation d'installation -- Comme d'autres logiciels payant comme Softaculous ou autres) qui rassemble des apps de tout horizon.
Dépôt Yunohost-Apps : https://github.com/YunoHost-Apps
Site Officiel : https://yunohost.org
Liste des apps par catégories : https://yunohost.org/#/apps_en
Début de packaging pour Roadiz : https://github.com/YunoHost-Apps/roadiz_ynh

PS : Des organisations comme Movim, LaBriqueInternet ou Duniter ont décidé de s'impliquer dans le projet de Yunohost et ont créé chacune leur propre app. Je suis moi-même membre du Groupe App.

**Comment by ambroisemaupate** [comment]
Si je fais la cmd de mon côté, il n’y a aucun souci.

Pourquoi devez-vous utiliser `sudo` pour executer php en CLI ?

```bash
vagrant@vagrant-ubuntu-trusty-64:/var/www$ bin/roadiz user:create abld
Email : win10@tutanota.com
Is user a backend user? [y/N]:
Is user a super-admin user? [y/N]:
User “abld”<win10@tutanota.com> created…
Password “X$5gYvSSG5f*”.
```

**Comment by frju365** [comment]
j'ai aussi essayé avec www-data (et en ajoutant un chmod 777) mais rien n'y fait : 
`
pi@yunohost:/var/www/roadiz $ sudo su - www-data -s /bin/bash -c "cd /var/www/roadiz && ./bin/roadiz user:create abld"
`
`
Email : win10@tutanota.com
`
`
Is user a backend user? [y/N]: 
`
`
Is user a super-admin user? [y/N]: 
`
 `                                                                    
  [Swift_RfcComplianceException]                                     
  Address in mailbox given [] does not comply with RFC 2822, 3.6.2.  
  `                                                                   
`
users:create <username>
`
`
pi@yunohost:/var/www/roadiz $
`

Peut-être que c'est parce que j'ai supprimé le install.php ?

**Comment by frju365** [comment]
Pour information je suis sur un raspberry pi 3 avec la version 1.6.2 de nginx (je ne sais pas si ça va vraiment aider car, en fait l'installation en graphique fonctionne) En tout cas j'affirme que l'idée d'une commande comme  : 
`bin/roadiz install-cli --ip-adress=0.0.0.0 --dbhost=localhost --dbuser=exemple --dbpass=1234 --dbname=roadiz --user_mail=ex@dom.tld --backend_user=y --admin_user=y`
Ce serait bien mais j'ai vraiment un niveau assez bas en PHP (mais je peux essayer, bien-sûr).

**Comment by ambroisemaupate** [comment]
Je crois savoir… si tu as installé Roadiz en full-CLI, tu ne dois pas avoir rempli le paramètre `email_sender`. Du coup au moment d’envoyer l’email avec le mot de passe généré il crée un message dont le header `From:` est vide.

**Comment by frju365** [comment]
ok... c'est peut-être ça. :) je vais aller regarder. Merci :)

**Comment by frju365** [comment]
But how can I reinstall it ?

**Comment by ambroisemaupate** [comment]
J’ai ajouté sur la version develop un mode non-interactif pour la création d’user.

`bin/roadiz users:create -n --email=test@test.com --password=secret --super-admin test`

Pour installer Roadiz en CLI, tu peux te baser sur le fichier `.travis.yml` qui fait grosso-modo ce que tu recherches mais sur notre Travis CI.

```shell
# Install with develop branch
composer create-project roadiz/standard-edition -s dev my-site;
cd ./my-site;
bin/roadiz themes:generate -n Awesome;
# Non interactive installation
bin/roadiz orm:schema-tool:create -n --env=install;
bin/roadiz install -n --env=install;
bin/roadiz themes:install -n "/Themes/AwesomeTheme/AwesomeThemeApp";
bin/roadiz themes:install -n --data "/Themes/AwesomeTheme/AwesomeThemeApp";
bin/roadiz cache:clear --env=install;
bin/roadiz cache:clear --env=dev;
bin/roadiz orm:schema-tool:update -n --force;
bin/roadiz themes:install -n --nodes "/Themes/AwesomeTheme/AwesomeThemeApp";
bin/roadiz cache:clear --env=install;
bin/roadiz cache:clear --env=test;
bin/roadiz cache:clear --env=dev;
bin/roadiz users:create -n --email=test@test.com --password=secret --super-admin test;
```

**Comment by frju365** [comment]
Merci Beaucoup. Je vais voir si tout fonctionne et je reviens pour vous dire le résultat.

En tout cas, MERCI ! :+1:
