### ISSUE TITLE
Langage choice in CLI Installation for admin interface

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#248]
Hello,
I had a new idea to complete the CLI installation (before adding the tag "working" for my package of yunohost) : Can you add a new choice for the CLI installation, the language with for example an argument like : `--default-language="fr"` ? Because the graphic installation integrates the installation of a default language (for the admin interface, I mean), the CLI must integrate this too, please. :smile:
Thanks,
frju365

**Comment by ambroisemaupate** [comment]
I’m closing suggestion issues. Feel free to reopen it on https://ask.roadiz.io/
