### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#249]
Hello,
I wanted to know if it's possible to have a LDAP integration... only for the users registration. I know it's a complicated feature... so for instance, I just give idea :smile: . If I know, how to integrate this, I will do a PR, but it's not sure. 
Thanks,
frju365

**Comment by ambroisemaupate** [comment]
See how to integrate `LdapUserProvider` in Roadiz DI.       http://symfony.com/doc/2.8/security/ldap.html

**Comment by ambroisemaupate** [comment]
I’m closing suggestion issues. Feel free to reopen it on https://ask.roadiz.io/
