### ISSUE TITLE
Another idea : Preview tab for page preview

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#250]
Hello,
I had a new idea this morning. Can you add a preview tab to show the page as it will be published. That is an awesome feature for users... because users sometimes have no idea if the page they are edited looks good or not.
Thanks,
frju365

PS: Just idea of feature. :smile:

**Comment by ambroisemaupate** [comment]
Hi @frju365 

Just use the `preview.php` entry point while connected as admin. You’ll see your actual website but with unpublished nodes displayed. 

It’s Roadiz philosophy not to mix up back-end and front-end. Backoffice must not know how its data is rendered so we won’t add "in-backoffice" preview. Imagine, your data can be rendered in HTML by one or two themes according to your domain-name. You can create a JSON-only theme if you want to create a REST API.

**Comment by ambroisemaupate** [comment]
Moreover, in Roadiz, you can create `reachable` node-type which represent an actual Page, Blog post… of your website. But you can also create non-reachable nodes, such as page-blocks, custom entities for your business logic, these nodes won’t be previewable as they will be rendered elsewhere.

**Comment by frju365** [comment]
yes... ok. It was just an idea... Thanks for your answer. I will use preview.php.

**Comment by frju365** [comment]
I need to learn more. Roadiz has many features and is an awesome software. Thanks for developing this.
