### ISSUE TITLE
Another idea : Resize image

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#251]
Hello (3 "hello" in a day),
I wanted to know if there are a possibility to resize the images the user add on the website ? because my header image is a bit too big... I saw it on other CMS, so it's perhaps a good feature to add in Roadiz.

Thanks, 
frju365

**Comment by ambroisemaupate** [comment]
That’s a front-end feature. Roadiz is made to host full size image, then with `|display` Twig filter you can serve any image sizes, fit, crop you want on-the-fly.

http://docs.roadiz.io/en/latest/developer/themes/display_documents.html

**Comment by frju365** [comment]
I will see the doc, even if I think it's a bit complicated and long. I was thinking of a Graphic feature, because the other users of my website, for example redactors(for a blog) or translators(static website) don't know anything about html, twig or php language... and they need surely to resize the image for the article. -- without having access to the server too. Or I don't understand the goals of roadiz perhaps...
