### ISSUE TITLE
missing vendor folder

### ISSUE THREAD

**Issue by simer1991** [roadiz/roadiz#255]
Hi 

I just downloaded roadiz zip from here and copied to my xamp folder. 

When i try to run the roadiz cms it give me error 
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\roadiz-master\index.php on line 42

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\roadiz-master\index.php on line 42

there is no vendor folder in the main folder.

Can please anyone help me with this.

**Comment by ambroisemaupate** [comment]
Did you run `composer install` before using it? We do not provide out-of-the-box ZIP archive anymore, you should use [roadiz/standard-edition](https://github.com/roadiz/standard-edition) instead.
