### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ziselive** [roadiz/roadiz#259]
New version of the program, remove the online quick install?

**Comment by ambroisemaupate** [comment]
??

**Comment by ziselive** [comment]
Virtual machines can not be installed?

**Comment by ambroisemaupate** [comment]
@ziselive Could you be a bit more precise? We can't help you with no informations at all.

**Comment by ziselive** [comment]
Can the program be installed only by the composer? Virtual space can not be installed.

**Comment by Gouterman** [comment]
Maybe you can increase your vm ram amount
