### ISSUE TITLE
Error after install on Windows 7 with WAMP Server 64

### ISSUE THREAD

**Issue by blackthorns** [roadiz/roadiz#262]
Hi,
Just after running the install and generate FooBar theme on WIndows 7 64bits, I have this error :

Generating autoload files
> php bin/roadiz composer:post-update
Do you want to copy default configuration file? [Y/n]

  [Symfony\Component\Console\Exception\RuntimeException]
  Aborted

composer:post-update

Script php bin/roadiz composer:post-update handling the post-update-cmd event re
turned with error code 1

The install.php file in /web is not generated and I can't go to the next step.
 
Would you know why I get this issue ?

Thanks a lot

**Comment by ambroisemaupate** [comment]
Hi @blackthorns, 

What terminal do you use ? Command invite ? Power Shell, Git terminal ? It seems te be an issue with Windows file system.

**Comment by ambroisemaupate** [comment]
https://stackoverflow.com/questions/28218932/migration-not-working-on-production-server-using-laravel-forge-with-error-run

It seems that Symfony console have trouble to read your response when typing Y or N. 

Try with another shell.

**Comment by blackthorns** [comment]
Hi, 
I use the traditional Windows command invite. I'll try another one, thanks !

**Comment by ambroisemaupate** [comment]
You should try to use a embedded terminal, such as *PHPStorm’s* or even passing to Windows 10 with their cool Linux compatibility stack.
