### ISSUE TITLE
Project in Russia

### ISSUE THREAD

**Issue by webdesignermsk** [roadiz/roadiz#265]
Want to develop a project in Russia, Moscow. All communities in Russia, learn about CMS

**Comment by webdesignermsk** [comment]
I already bought the domain roadiz.ru waiting for Your consent.

**Comment by ambroisemaupate** [comment]
**Roadiz is a registered trademark in Europe**

You can register roadiz outside of EU.

**Comment by webdesignermsk** [comment]
Can I have your support, help on orders with my clients and stuff?

**Comment by elodiearnouk** [comment]
Hello @webdesignermsk ! @ambroisemaupate will probably revert back to you but *Roadiz* is an open-source CMS developed in-house by our studio, Rezo Zero. It is the base to most - almost all - of our websites. Therefore, we do not provide support as this is a tool to our workflow, not a product we sell and/or market.
Shall you have questions, we'll probably reply in the best of our abilities - just like we do to any developer using *Roadiz* - but we don't provide assistance, third party maintenance or anything else. It's open-source so, by definition, the point is to have autonomous users that contribute and help perfect *Roadiz*!

**Comment by webdesignermsk** [comment]
My customer wants to get on your CMS strictly, and wants the meaning to make a similar site http://www.mrassociates.org/ .Can I get help with my template for this site? Or at least a work plan where to start? asking for your help.

**Comment by ambroisemaupate** [comment]
All of Rezo Zero website are original creations and front-ends are built from scratch. We do not provide ready-made templates to protect our customers copyright. 

We encourage you to start with our `BaseTheme` as a fresh starter using `themes:generate` CLI command. All the architecture is up to you, the main motto for all our creations is modularity. For example using *page/block* pattern: http://docs.roadiz.io/en/latest/developer/themes/custom_assignations.html?highlight=page%2Fblock#use-page-block-data-pattern

**Comment by webdesignermsk** [comment]
Thank you very much...
