### ISSUE TITLE
Impossible to disable debug panel

### ISSUE THREAD

**Issue by ciajulius** [roadiz/roadiz#268]
Situation: I'm creating new theme, creating blocks in it, etc., testing how it will look for end user, and there is this debug bar, with no style (and I will never style it), in the middle of my page. I must hide it using css. Parameter `display_debug_panel` does not seem to do anything.
By disabling debug panel in settings, it should be disabled when browsing using index.php, preview.php, dev.php.

Also, debug panel could be about the same as in silex or symfony, it gives more information there, but that's another issue, I think.

**Comment by ambroisemaupate** [comment]
http://phpdebugbar.com/docs/

**Comment by ambroisemaupate** [comment]
![capture d ecran 2017-06-19 a 15 01 26](https://user-images.githubusercontent.com/380026/27286375-37b8b634-5500-11e7-8f34-08002dbf7502.png)

@ciajulius  It’s fixed on *develop* branch. Ready for next release.

**Comment by ciajulius** [comment]
@ambroisemaupate When will this be implemented?

**Comment by ambroisemaupate** [comment]
It’s already implemented on **develop** branch. We are waiting to release a new Roadiz version.

**Comment by ciajulius** [comment]
But why wasn't this implemented in 0.19.2, 0.19.3, 0.19.4 or 0.19.5?

**Comment by ambroisemaupate** [comment]
Because as the version numbers say… they’re *hotfixes* so no new features in them.

**Comment by ciajulius** [comment]
Hrm. But isn't this a bug, that option exists, but it does nothing? You even used word "fixed" above in one of the comments :) but alright, I'll wait for next release. Thanks!

**Comment by elodiearnouk** [comment]
Hello @ciajulius :) - The next release should happen soon! Remember it's open-source we're talking about it here though. So either we develop it - or you do, we "fix" it - or someone else does, and we basically all share improvements whenever we can. Have a great day!
