### ISSUE TITLE
Error with node type field name preview

### ISSUE THREAD

**Issue by martial** [roadiz/roadiz#271]
There can be a different node type field name in the preview ( using ALT key ) – when using caps letters during creation.

`media_download` is generated but show `mediaDownload` using the ALT key

**Comment by ambroisemaupate** [comment]
Yes the getters setters will always *camelize* your node type field name. So protected field stays `media_download` (for custom query builders use that), and methods will be `getMediaDownload` and `setMediaDownload` so that you can use them in Twig templates as `nodeSource. mediaDownload`.
