### ISSUE TITLE
installer problem

### ISSUE THREAD

**Issue by jakesullyneytiri** [roadiz/roadiz#294]
I was installing this script but problem is when i finished the installer i deleted the install.php as it told me todo. But once i go to index of domain it gives me the installer page still, i have now ran it for 2nd time filled everything out and then clicked finish and it said again that i can now delete install.php, but i don't have any install.php this time.

So i reloaded the page and for 3rd time yet installer page comes up again. Idk whats wrong since it keeps taking me back to installer everytime and not the actuall installed site.

How do i fix this?

/Thanks

**Comment by ambroisemaupate** [comment]
Hi @jakesullyneytiri 

What is your environment? Vagrant? Docker? MAMP? XAMP?
Did you launch the installation from /install.php entry point ?

It seems that your PHP runner don't see any change made to your disk. Do you have APC or XCache installed ?

Install.php file can be keeped after installation is done, you should just change your entry point to prod (`/`) or dev (`dev.php`).

Do you managed to launch /dev.php entry point ?

**Comment by jakesullyneytiri** [comment]
i installed it on cpanel/whm since i once had it working there. But this time it wouldn't work. Since i keep getting installer page back :/

**Comment by ambroisemaupate** [comment]
Do you use *Standard edition* ?   
Did you configured your apache/nginx host to redirect your requests to `web/index.php` ?

**Comment by jakesullyneytiri** [comment]
i'm using the copy from the github, then i ran cmd composer install to create install.php and then i added my ip in file to be able to view it so i could run installer. This is then where problem begun. That the installer keept coming back.

**Comment by ambroisemaupate** [comment]
> Also when i run composer install it tells me this as well "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

It’s just a warning, it should not prevent from installing entry points files.

> Update 2: I'm getting installer on both index.php and dev.php, it just won't let me visit my website -.-

It’s definitely a vhost problem, you should update your *CPanel Apache* or *Nginx* configuration to redirect all requests to index.php entry-point.

Then, you definitely should use *standard-edition*, it’s the same workflow as any *Symfony* project. I doubt *CPanel* is not compatible with *Symfony* based configuration.

https://stackoverflow.com/questions/46511247/how-to-deploy-symfony-on-cpanel-in-public-html

A simple .htaccess in your cpanel `public_html` should work.

**Comment by jakesullyneytiri** [comment]
what about part where composer tries to run http://localhost/clear_cache.php ? since i think this could be problem to why installer comes up all the time since cache isn't cleared by the script itself.

**Comment by ambroisemaupate** [comment]
You can remove them in your `composer.json` ligne 126-127. Or update them to add `-d` argument to specify the domain instead of *localhost* with your actual domain.

```
php bin/roadiz cache:clear-fpm -e prod -d mydomain.com
```

 bin/roadiz cache:clear-fpm calls `clear_cache.php` entry point to use PHP-FPM real cache. These caches can’t be purge from CLI with `cache:clear` command.

**Comment by jakesullyneytiri** [comment]
added it but this time it couldn't read it as code 0 and it nagged about could not connect to a database.

**Comment by ambroisemaupate** [comment]
Closing issue, if needed reopen your issue on https://ask.roadiz.io/ for 1-to-1 help desk.
