### ISSUE TITLE
What about a nice forum to developp Roadiz ?

### ISSUE THREAD

**Issue by frju365** [roadiz/roadiz#299]
Hello,
I'm working on a Roadiz theme (in a theme powered by this CMS or Framework), but I've some problem, like knowing PHP or CSS compiler system. So, I found an idea : Why not making discussions on a forum ?

**Goals** : 
- Making work with Roadiz easier and not pollute Github Issues system. 
- Discussion about support, about website, about PHP/JS/CSS/SCSS/New features.
- Introduction of existing Working website, Themes : Ideas ?
- and because we need that : Roadiz is a bit complex, but with motivation we could make big work.

I know it could make problem to you company, Rezo Zero, which is one, from my point of view, of the BEST company which works for developing Website. But there are many **advantages** for you in making one : 
- Making ads for Roadiz, as the best software, still in beta.
- Developing new features for Roadiz, because Ads = New Users = New Devs = New Features/Better Security/Internationalization = more Websites = more ads ... 
- Motivation for ppl who doesn't know what is Roadiz... Complicated to have a website with roadiz, but "let's see if backend is so complicated when ppl help me".
- Open a market and you could want in a future to extend Roadiz.

**We have already Gitter ! Why a forum ? who will maintain it ? No time for it ?**:
- Gitter is good but we need to scroll up to see old discussion, and I saw many time that persons had problem with the same origin or which are not so different.
- A forum is more attractive
- Maintaining a forum can be made by dev at the beginning but can quickly evolved to a community forum where the maintainers will be persons of the community.

So, could it be good to have a forum ? It's just an idea, "not because every communities have one", but because it's strategical.

Thanks in advance for your answer,
frju365

PS: sorry for my bad english. :)

**Comment by ambroisemaupate** [comment]
Hi @frju365 

Thanks for your detailled suggestion!

I understand an agree with you about having a place to ask questions which is not Github issues and which is neither a chatroom. But Rezo Zero does not have the time to create a forum from scratch and to make it live. We are currently two active contributors on Roadiz core, working with @Gouterman on VueJS transition for backend interface. 

I’ve looked at StackExchange platform to build a forum without *developing* it. But we are not enough people to create a dedicated space: http://area51.stackexchange.com/ Each new Q&A site must be requested in a pooling area and must match the minimum requirements: https://area51.meta.stackexchange.com/questions/20966/minimum-activity-requirements-for-area-51   
I think it’s a better idea to build Roadiz community on an existing platform with lots of active developers. 

Thus, we need to enhance features that are specific in Roadiz to make it a relevant open-source product beside all **modern** CMS built on Symfony/Silex/Laravel/… So, UI, backend design and end-user experience are, for the moment, key features that make Roadiz relevant when other CMS are more or less user-friendly. But we still have a steep learning curve for initial setup and deployment. We master these parts at Rezo Zero using *Docker* and *Gitlab CI/CD* tools but it won’t never be as easy as copying files on your FTP like *[Kirby](https://getkirby.com/)* or other *no-DB* CMS. So, at the same time we need to improve Roadiz documentation with more examples and *why-not* some videos to show how to setup it or deploy it on production. 

At the end, forum will be useful for practical cases and theming which are harder to explain in a generic documentation.

**Comment by frju365** [comment]
Yes. I agree with you. In fact, I was not thinking of building something from scratch. There are many forums software which are very easy to use/customize and very nice ;-). For example : NodeBB(https://nodebb.org/), Discourse(https://www.discourse.org/) or Flarum(https://flarum.org) which are the three best forum softwares from my point of view(many features, many extensions, easy-to-setup...)

If you want I can try buy a VPS and try to install one of this forum softwares. But of course, it is a proposition. Roadiz, is perhaps not user-friendly... but it's like linux CLI, when you know all the command and know every advantages of this, you understand that it's not so evil. ;-)

**Comment by ambroisemaupate** [comment]
@frju365 *Flarum* seems very cool, and UI is clean 😁

We’ll look at it closely.    
But do not buy a VPS, we already have a dedicated server for our tools, and if a Docker image exists, we can easily deploy onto it.

The only con is that a self-hosted forum won’t be as visible as an existing SaaS forum solution as StackOverflow (existing user, traffic…). But it will become visible (SEO) after some time.

@azokal @Gouterman @julienrezo @elodiearnouk @notorigine @maximeberard What do you think?

**Comment by notorigine** [comment]
I think it's a brilliant suggestion, it will just make it easier for anyone using Roadiz to ask questions and get actual answers from other people; Gitter was a nice start but after a while everything gets burried in a flood of messages.
From strategical standpoint, it also makes sense to have a dedicated forum-like space 🙂

Have you guys thought of a dedicated Slack channel maybe? I know Craft has one for example, it's pretty nice and active to be fair, although I guess it falls back into the "chat room" dilemma. At least you could create channels devoted to only PHP issues; JS issues and so on…

**Comment by Ashugeo** [comment]
Many active communities have a Slack workspace indeed, and that's pretty useful when you try out a new tool and need help from people who have used it for a while – or even the developers team. But that works only if that tool has a community that's big enough to have people spread their knowledge, instead of the devs constantly answering question on their free (or work) time.

A forum would make sense IMO because it's meant to have threads, tags, strong search features, and so on. Slack is more of an instant messaging app to get some help quickly on specific matters. Both can be useful, it's just not the same use!

**Comment by ambroisemaupate** [comment]
Ok guys, https://ask.roadiz.io/ is up
