### ISSUE TITLE
Empty Explorer when I make "Children nodes" and "Nodes references" type in the back-office

### ISSUE THREAD

**Issue by rmartis** [roadiz/roadiz#302]
Problem started with roadiz beta 0.22.0.
![rz-wrong](https://user-images.githubusercontent.com/22616248/37511404-f706a190-28fe-11e8-8af5-d8511c9bfc1f.png)

**Comment by ambroisemaupate** [comment]
```
Class "Themes\Rozier\Forms\NodeType" sub class of "Symfony\Component\Form\AbstractType" 
is not a valid entity or mapped super class.
```

Arg, it’s a silly refactoring mistake, wrong namespace, hotfix is coming very soon @rmartis .

thank you for your report.

**Comment by ambroisemaupate** [comment]
`composer update` and you’re good to go!
