### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fatemeh0021** [roadiz/roadiz#306]
hi i have a problem with installing roadiz .....

require(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wamp64\www\index.php on line 42
--

require(vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp64\www\index.php on line 42
--

**Comment by ambroisemaupate** [comment]
Hi @fatemeh0021 

Did you install standard-edition or plain sources Roadiz ?

It seems that you did not install Composer !

http://docs.roadiz.io/en/latest/developer/first-steps/installation.html

**Comment by fatemeh0021** [comment]
i have wamp on my system.
how can i have PHP on path?
