### ISSUE TITLE
Distinguer le nom des noeuds dans la recherche

### ISSUE THREAD

**Issue by ghost** [roadiz/roadiz#390]
![image (69)](https://user-images.githubusercontent.com/83358667/116427035-f3b60680-a843-11eb-87a5-21847314422f.png)

**Comment by ambroisemaupate** [comment]
Add `parent.nodeName` the same way Node explorer does. Even if we have to reduce result count.

**Comment by ambroisemaupate** [comment]
Fixed in v1.5.24 and v1.6.16
