### ISSUE TITLE
Implement a backup command usable with crontab

### ISSUE THREAD

**Issue by azokal** [roadiz/roadiz#5]
```
bin/roadiz backup --all;

bin/roadiz backup --files;
bin/roadiz backup --database;
bin/roadiz backup --config;
```

This command must generate a zip file in the specify command.
It must containt:

* the folder "files/"
* the database dump
* the configuration file

The archive must be name by time.

Doing the import command too.

**Comment by ambroisemaupate** [comment]
Won’t fix
